version: "3"
services:
  server:
    build: server
    volumes:
      - ./server:/app
    env_file:
      - .env
    ports:
      - ${PORT}:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
