version: "3"
services:
  server:
    build: server
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
